### PR TITLE
Id filter

### PR DESCRIPTION
**Pull request by msplr**
This implements a minimal filter functionality for the CAN bridge.
The CAN frame packing has also slightly changed: command arguments are now packed into a MessagePack array.

### CODE REVIEW

**Comment by antoinealb** [comment]
What kind of changes should be put in the bootloader ? I wonder if we shouldn't put the Python implementation in this repository too. What do you think ?

**Comment by msplr** [comment]
The CAN frames and the filter list are now encoded as a MessagePack array instead of a sequence of single objects. 
I added a data length field to the CAN frame, such that the length isn't determined by the actual number of data bytes, which would be weird for a remote frame where data length is zero.
In addition, the filter command needs to be implemented.

I agree, it is best if we put the python implementation into this repo.

**Comment by antoinealb** [comment]
I don't know if it is really useful to have a separate length field. MessagePack already seems to handle this case. But I guess it cannot hurt.

Do you think we can merge this before including the python implementation ?

**Comment by msplr** [comment]
In a CAN remote frame the data is 0 bytes, but the data length code holds the expected data length, this is why the length field is not always corresponding to the data length.
It doesn't make sense to send garbage data just to tell the length value of the remote frame.

Yes, I think we can safely merge, since we're tracking with submodules.

**Comment by antoinealb** [comment]
oh ok did not know that there can be CAN frames where len(data) != data_len...

I will extract the python implementation here soon. Merging it for now.

**Comment by msplr** [comment]
We need the updated python implementation for testing.

**Comment by Stapelzeiger** [comment]
#critical

**Pull request merged**
